### ISSUE TITLE
proper import for ezvcard in all modules

### ISSUE THREAD

**Issue by sluebbers** [inofix/ch-inofix-contact-manager#17]
current import works for compilation, but seem to block each other when deploying all three modules.

**Comment by chrberndt** [comment]
Probably the initial mistake was a wrong dependency configuration in the api and service module. EzVcard and it's dependencies had been configured with "compile" instead of "compileOnly" . With "compileOnly" all modules are deployable and the EzVcard library is available in the deployed module (tested for contact-manager-web in the portlets update() method).

**Comment by sluebbers** [comment]
thank you, christian

**Comment by chrberndt** [comment]
Works only as a workaround but does not fix the underlying problem. 

We will now try two alternative strategies: 

Christian will go for Option 4 of 
https://web.liferay.com/de/web/user.26526/blog/-/blogs/osgi-module-dependencies

Stefan will try to build an OSGI-Module of the ezVCard jar, which 
- includes the transitive? dependencies (is this the right terminology?)
- is deployable via the Felix GoGo Shell (see: https://dev.liferay.com/develop/reference/-/knowledge_base/7-0/using-the-felix-gogo-shell) 
- is usable by the different contact-manager modules

**Comment by chrberndt** [comment]
Updated deploy instructions can be found at 

https://github.com/inofix/ch-inofix-contact-manager

except for the vinnie-module, the JARs available at maven central are already valid osgi modules which are ready to be deployed to Liferay.

The module's bnd-configuration has been adjusted.
